@backend_HostAddress = http://localhost:5007

### WeatherForecast endpoints
GET {{backend_HostAddress}}/weatherforecast/
Accept: application/json

###

### User endpoints

### Create a new user
POST {{backend_HostAddress}}/api/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "password": "password123"
}

###

### Get all users
GET {{backend_HostAddress}}/api/users
Accept: application/json

###

### Get user by ID
GET {{backend_HostAddress}}/api/users/1
Accept: application/json

###

### Get user by email
GET {{backend_HostAddress}}/api/users/by-email/john.doe@example.com
Accept: application/json

###
